
language: R

sudo: false

cache: packages

r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --no-vignettes"

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change
