---
title: "Getting Started"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  cache = TRUE
)
```

```{r, message=FALSE}
library(usps)
library(dplyr)
library(tidyr)
library(ggmap)
library(zipcode)
```

```{r, message=FALSE}
# data(zip_zones)

zip_zones <- 
  readr::read_csv(here::here("data", "2018-06-19_zip_zones.csv"))

names(zip_zones) <- 
  c("origin_zip", "dest_zip", "zone", "specific_to_priority_mail",
    "same_ndc", "has_five_digit_exceptions")
```


```{r}
data(zipcode)

zips <- 
  zipcode %>% 
  as_tibble() %>% 
  mutate(
    zip_trim = substr(zip, 1, 3)
  )
```

```{r}
usps_zips <-
  tibble(
    zip =
      unique(zip_zones$origin_zip) %>% 
      c(unique(zip_zones$dest_zip)) 
  ) %>% 
  distinct()
```


```{r}
zips_lat_long <- 
  zips %>% 
  distinct(zip_trim, .keep_all = TRUE) %>% 
  left_join(usps_zips, by = "zip") %>% 
  select(zip_trim, latitude, longitude)
```


```{r}
zip_zones_lat_long <- 
  zip_zones %>% 
  left_join(zips_lat_long, by = c("origin_zip" = "zip_trim")) %>% 
  rename(
      lat_origin = latitude,
      long_origin = longitude) %>% 
  left_join(zips_lat_long, by = c("dest_zip" = "zip_trim")) %>% 
  rename(
      lat_dest = latitude,
      long_dest = longitude) %>% 
  drop_na(zone)

zip_zones_lat_long
```


```{r, eval=TRUE}
us <- 
  # get_googlemap("us", zoom = 4)
  get_map("us", zoom = 4, maptype = "toner-lite")
```


```{r, eval=TRUE}
# pal <- wes_palette("Royal2")

ggmap(us) +
  geom_polygon(data = zip_zones_lat_long %>% 
                 mutate(zone = factor(zone)) %>% 
                 filter(origin_zip == "112"), 
             aes(long_dest, lat_dest, fill = zone),
             alpha = 0.5) +
  labs(x = "", y = "", fill = "Zone", subtitle = "Origin zone prefix: 112") +
  ggtitle("Shipping Zones from NYC") +
  scale_fill_brewer(type = "seq") +
  theme_classic(base_family = "Arial Narrow")
  # scale_fill_discrete(c("#9A8822", "#F5CDB4", "#F8AFA8", "#FDDDA0", "#74A089",
  #                     "#FF0000", "#00A08A", "#F2AD00", "#F98400"))
  
  # stat_density2d(data = party_ready, 
  #                aes(x = longitude, y = latitude,  fill = ..level.., alpha = ..level..), 
  #                geom = "polygon")
```


<br>
